# support two different method: "Z_SCORE" , "MIN_MAX"
ran-cal-method: Z_SCORE

# require played times to have rank
require-plays: 20

# reset time (24 hours)
update-time: 00:00

# ranking data showing format
info-message:
  - "&bplayer: &e<name>"
  - "&brank: &e<rank>"
  - "&bscores: &e<score>"
  - "&bn-scores: &e<n-score>"
  - "&bplayed: &e<plays>"

# whether to make it only for show info but not calculate
show-info-only: false

# if disabled, this plugin will not handle any save
handle-data-save: true

# default calculated format
default-calculate-format: "<kills> * 50 - <deaths> * 20"

#Unranked tag
unranked-tag: "UnRanked"

#rankup title
rankup-subtitle: "&k&a||&e RANK UP &k&a||"

#rank updated msg,can be either rank up or rank down
rank-updated-msg: "&bRank data has been updated。"