name: PvPRanking
main: com.ericlam.mc.ranking.main.PvPRanking
version: 1.1.9
author: Eric Lam
softdepend: [PlaceholderAPI]
permissions:
  pvprank.admin:
    default: op
    description: modify rank data
    children:
      - pvprank.info
      - pvprank.reset
      - pvprank.help
      - pvpdata.info
      - pvpdata.reset

commands:
  pvprank:
    description: pvp rank command
    aliases: [rank, pvpranking]
  pvpdata:
    description: pvp data command
    aliases: [data, pvprankingdata]