name: PvPRanking
main: com.ericlam.mc.ranking.main.PvPRanking
version: 1.0.0
author: Eric Lam
permissions:
  pvprank.admin:
    default: op
    description: modify rank data
commands:
  pvprank:
    description: pvp rank command
    aliases: [rank, pvpranking]